### ISSUE TITLE
Console is not updated

### ISSUE THREAD

**Issue by ghost3666** [dragonked2/Egy-Crack#4]
https://user-images.githubusercontent.com/66541902/244477725-cf66786e-23c4-432c-a870-d438d07711ee.png

the V2 is not displaying any ethereum address on console just progress how many keys generated so how can i know its being checked with eth.txt file

![image](https://github.com/dragonked2/Egy-Crack/assets/93757049/cebcdc59-f220-41f6-93cf-8a227918bf7d)

**Comment by dragonked2** [comment]
its working Perfectly 
but we dont show the attemptes in realtime screen to improve performance and speed of the script
also dont forgot to update your discord webhook if the script required it

**Comment by ghost3666** [comment]
My question remains, so how many words/s or how many tries per seconds

**Comment by dragonked2** [comment]
yes its depends on your system and hardware capabilities there is no stable number i can say
its not working on words/s
its generate address randomly or sequential 

and current speed you can see at the progressbar

**Comment by ghost3666** [comment]
any lucky guess?? if we have a 3gb address list
